/**
 * DOCS BUILD — `docs/*.md` is the source of truth, `src/docs.ts` is output.
 *
 * The docs ship INSIDE the package rather than on a website, because a
 * consumer that renders the docs surface must never be documenting a version
 * other than the one it installed. Markdown files are what humans edit;
 * this script freezes them into a typed module so `import { DOCS } from
 * '@myavenceo/aven-vibes/docs'` needs no filesystem, no loader plugin and no
 * fetch — the same purity rule the rest of the package lives by.
 *
 * Ordering comes from the numeric filename prefix (`01-...`, `02-...`), the
 * slug from the rest of the filename, the title from the first h1, and the
 * summary from the first paragraph. Deriving instead of duplicating means a
 * section cannot disagree with its own metadata.
 *
 * Run by `bun run build` BEFORE tsc, so the generated module always exists
 * and always compiles with everything else.
 */
import { readdir, readFile, writeFile } from 'node:fs/promises'
import { join } from 'node:path'

const DOCS_DIR = new URL('../docs', import.meta.url).pathname
const OUT_FILE = new URL('../src/docs.ts', import.meta.url).pathname

type DocSection = { slug: string; title: string; summary: string; body: string }

/** The first h1's text, or a loud failure — a section without a title is unfinished. */
function extractTitle(body: string, file: string): string {
	const match = body.match(/^#\s+(.+)$/m)
	if (!match) throw new Error(`${file}: no h1 found — every section leads with its title`)
	return match[1].trim()
}

/**
 * The first paragraph after the h1: the first block that is neither blank,
 * a heading, nor a fence. Newlines inside the paragraph collapse to spaces,
 * because the summary renders in cards and sidebars, never as markdown.
 */
function extractSummary(body: string, file: string): string {
	const lines = body.split('\n')
	const paragraph: string[] = []
	for (const line of lines) {
		const trimmed = line.trim()
		if (paragraph.length === 0) {
			if (trimmed === '' || trimmed.startsWith('#') || trimmed.startsWith('```')) continue
			paragraph.push(trimmed)
		} else {
			if (trimmed === '') break
			paragraph.push(trimmed)
		}
	}
	if (paragraph.length === 0) throw new Error(`${file}: no opening paragraph found`)
	return paragraph.join(' ')
}

const entries = (await readdir(DOCS_DIR)).filter((f) => /^\d+-.*\.md$/.test(f)).sort()
if (entries.length === 0) throw new Error(`no numbered markdown files in ${DOCS_DIR}`)

const sections: DocSection[] = []
for (const file of entries) {
	const body = await readFile(join(DOCS_DIR, file), 'utf8')
	const slug = file.replace(/^\d+-/, '').replace(/\.md$/, '')
	sections.push({
		slug,
		title: extractTitle(body, file),
		summary: extractSummary(body, file),
		body
	})
}

const header = `/**
 * GENERATED FILE — do not hand-edit.
 *
 * Source of truth: the markdown files in \`docs/\` at the repository root.
 * Regenerated by \`scripts/build-docs.ts\`, which runs as part of
 * \`bun run build\`. Edit the markdown, not this module.
 */

/** One documentation section, in reading order. */
export type DocSection = {
	/** Stable URL-safe identifier, from the source filename. */
	slug: string
	/** The section's h1. */
	title: string
	/** The first paragraph, for cards and sidebars. */
	summary: string
	/** The full markdown source, for \`renderMarkdownDoc\`. */
	body: string
}

export const DOCS: DocSection[] = `

const source = `${header}${JSON.stringify(sections, null, '\t')}\n`
await writeFile(OUT_FILE, source)

/* The output is source code and CI lints source code, so the generator is
   responsible for emitting it already formatted — otherwise every regeneration
   is followed by a manual format step someone forgets. */
Bun.spawnSync(['bunx', 'biome', 'format', '--write', OUT_FILE])
console.log(`wrote ${OUT_FILE}: ${sections.length} sections`)
