/**
 * The generators every surface runs to derive its brand files from a `Brand`.
 *
 * These live IN the kit rather than in either repo's scripts folder, so the
 * app, the id service and the website all emit their theme from the same code
 * — a consumer cannot accidentally generate a different shape. Each repo keeps
 * only a thin script that calls these and writes the result where it belongs.
 *
 * Output is committed in the consuming repo. That is the whole guarantee: if a
 * hex is edited anywhere but `tokens.ts`, re-running the generator restores it
 * and `git status` is dirty, so drift fails a check instead of shipping.
 */
import { type Audience, assertNoShadowedTokens, type Brand } from './types.js'

/**
 * Build this brand's stylesheet generators.
 *
 * A factory for the same reason `createUtilities` is one: the tokens a theme
 * emits belong to the brand, the emitting does not.
 */
export function createGenerator(brand: Brand) {
	assertNoShadowedTokens(brand)

	const TONES = brand.tones
	const CREAMS = brand.creams
	const SURFACES = brand.surfaces
	const ROLES = brand.roles
	const SITE_ROLES = brand.siteRoles
	const APP_ROLES = brand.appRoles
	const FONT_STACK = brand.fonts
	const FONT_WEIGHTS = brand.fontWeights
	const RADII = brand.radii
	const SCALE_TOKENS = brand.scaleTokens
	const COMPONENTS = brand.components
	const PRIMITIVES = brand.primitives
	const APP_ICON_PLATE = brand.appIconPlate
	/** Which surface a theme is being generated for. */
	type ThemeVariant = Audience

	const BANNER = `/* GENERATED by ${brand.name} via @myavenceo/aven-brandkit — do not edit.
 * Every value here comes from the ${brand.slug} brand definition.
 * Re-generate with \`bun run brand:generate\`; edits are overwritten. */`

	function block(title: string, entries: Array<[string, string]>): string {
		const body = entries.map(([k, v]) => `\t--color-${k}: ${v};`).join('\n')
		return `\t/* ══ ${title} ══ */\n${body}`
	}

	/**
	 * The Tailwind `@theme` block: tones, creams, surfaces and roles.
	 *
	 * The `web` variant adds the two roles only the marketing site owns (`accent`,
	 * `offer`) and may point the font stack at a different build of the same
	 * face. Everything else is identical by
	 * construction — which is what the site's old "copy blocks 1–3 across" comment
	 * was asking a human to do by hand.
	 */
	function themeCss(variant: ThemeVariant): string {
		const font = variant === 'app' ? FONT_STACK.app : FONT_STACK.web
		const roles = variant === 'web' ? { ...ROLES, ...SITE_ROLES } : { ...ROLES, ...APP_ROLES }
		/*
		 * One `:root`, always.
		 *
		 * Two thirds of this used to be wrapped in `@theme`, which was a Tailwind
		 * directive and is now nothing at all. It cost more than a keyword: Tailwind
		 * TREE-SHOOK `@theme`, dropping any variable it saw no utility for, which
		 * silently deleted half the type scale and forced the scales into a second
		 * `:root` block below to survive. With the dependency gone, the split has no
		 * reason to exist and the scales come home.
		 *
		 * The variant now chooses only what it should ever have chosen: which roles
		 * this surface gets, and which font stack.
		 */
		const open = ':root {'

		const parts = [
			BANNER,
			'',
			open,
			'\t/* The four family tokens stay SEPARATE even where a brand points',
			'\t * several of them at one face, so introducing a dedicated display,',
			'\t * serif or mono face is one line in the brand and no change to any',
			'\t * component. */',
			`\t--font-sans: ${font};`,
			`\t--font-display: ${FONT_STACK.display ?? font};`,
			`\t--font-serif: ${font};`,
			`\t--font-mono: ${font};`,
			'',
			...Object.entries(FONT_WEIGHTS).map(([k, v]) => `\t--${k}: ${v};`),
			'',
			block('1 · THE BRAND TONES — the paint, each spelled exactly once', Object.entries(TONES)),
			'',
			block('the cream family, lightest to warmest', Object.entries(CREAMS)),
			'',
			block('2 · THE SURFACES — which rung each part stands on', Object.entries(SURFACES)),
			'',
			block('3 · THE ROLES — what a colour MEANS', Object.entries(roles)),
			'',
			...Object.entries(RADII).map(([k, v]) => `\t--${k}: ${v};`),
			'',
			...[
				'/* ══ 4 · THE SCALES — type, tracking, emphasis, elevation, geometry ══',
				' * A value that is not on a scale is not available. Before these, one',
				' * idiom was written fourteen ways and the type ramp was thirty arbitrary',
				' * sizes mixing px and rem by eye. */'
			].map((line) => `\t${line}`),
			...Object.entries(SCALE_TOKENS).map(([k, v]) => `\t--${k}: ${v};`),
			'}',
			''
		]
		return parts.join('\n')
	}

	/**
	 * The shared components as real CSS classes.
	 *
	 * aven-ui applies `COMPONENTS` directly as a `StyleDef`; the Tailwind surfaces
	 * cannot, so they get the same definitions emitted here as an `@layer
	 * components` stylesheet. One definition, two delivery mechanisms — which is
	 * the only way a card can be guaranteed to look the same in the app, the id
	 * service and the website.
	 */
	/**
	 * Turn one config entry into CSS, following nesting wherever it goes.
	 *
	 * A key that starts with `&` or `@` opens a NESTED rule rather than setting a
	 * property — `&:hover`, `&:has(> img)`, `@container (width < 20rem)`, `@media
	 * print`. That is what lets the config express what modern CSS can express;
	 * without it the emitter could only produce flat property bags, and anything
	 * with a state or a query had to be hand-written as a string literal beside the
	 * generated output. There was exactly one such literal (`button:hover`) and it
	 * is now config like everything else.
	 *
	 * Emitted as native nesting rather than flattened selectors, because the whole
	 * point is to stop generating a 2019 stylesheet on a platform that reads the
	 * nested form directly.
	 */
	function emitRule(selector: string, decls: Record<string, unknown>, depth = 1): string {
		const pad = '\t'.repeat(depth)
		const inner = '\t'.repeat(depth + 1)
		const lines: string[] = []
		const nested: string[] = []

		for (const [key, value] of Object.entries(decls)) {
			if (value && typeof value === 'object' && !Array.isArray(value)) {
				// `&:hover` / `@container …` — a rule, not a declaration.
				nested.push(emitRule(key, value as Record<string, unknown>, depth + 1))
				continue
			}
			const property = key.replace(/[A-Z]/g, (c) => `-${c.toLowerCase()}`)
			lines.push(`${inner}${property}: ${String(value)};`)
		}

		const body = [...lines, ...(nested.length ? ['', ...nested] : [])].join('\n')
		return `${pad}${selector} {\n${body}\n${pad}}`
	}

	function componentCss(): string {
		return [
			BANNER,
			'',
			'/* Cascade layers, so a component never has to out-specify a utility and',
			' * nothing here needs `!important`. Order is the priority order.',
			' *',
			' * `reset` and `base` join the list now that the reset is ours rather than',
			' * Tailwind preflight. A layer used but never DECLARED here is appended',
			' * after every declared one, so leaving the reset off this line would have',
			' * given it the last word over every utility in the codebase — a reset that',
			' * wins is not a reset. */',
			'@layer reset, tokens, base, primitives, components, utilities;',
			'',
			'@layer primitives {',
			'\t/* The shapes almost every layout is made of. Each is one idea, tuned',
			'\t * at the call site through a custom property rather than by adding a',
			'\t * class per value — the native answer to gap-2/gap-4/gap-6. */',
			Object.entries(PRIMITIVES)
				.map(([name, decls]) => emitRule(`.${name}`, decls as Record<string, unknown>))
				.join('\n\n'),
			'}',
			'',
			'@layer components {',
			Object.entries(COMPONENTS)
				.map(([name, decls]) => emitRule(`.${name}`, decls as Record<string, unknown>))
				.join('\n\n'),
			'}',
			''
		].join('\n')
	}

	/**
	 * Element defaults for surfaces that write plain HTML.
	 *
	 * The id service styles `h1`, `button` and `label` directly rather than reaching
	 * for a class, which is the right call for a handful of small, mostly-static
	 * screens — and it means the shared type has to arrive at element level or not
	 * at all. Each rule is the component definition of the same name, so a bare
	 * `<h1>` gets `title` and a bare `<button>` gets `btn` without touching markup.
	 *
	 * Emitted separately from `componentCss` because most surfaces do NOT want
	 * this: the app and the website put classes on everything, and element-level
	 * defaults would fight their utilities.
	 */
	function elementCss(): string {
		const pairs = Object.entries(brand.elements)
		return [
			BANNER,
			'',
			'@layer components {',
			pairs
				.filter(([, component]) => COMPONENTS[component])
				.map(([selector, component]) =>
					emitRule(selector, COMPONENTS[component] as Record<string, unknown>)
				)
				.join('\n\n'),
			'}',
			''
		].join('\n')
	}

	/* ══ ICONS ═════════════════════════════════════════════════════════════════
	 * Two primitives, both derived from ONE file: `assets/logo.svg`.
	 *
	 *   logo.svg ─┬─→ favicon.svg    the clean mark, squared
	 *             └─→ app-icon.svg   the same mark on a rounded brand plate
	 *
	 * The app icon used to be a hand-kept second copy of the logo's fourteen paths,
	 * pre-translated into an 800×800 frame. Editing the logo left it silently
	 * stale. Composing with a `<g transform>` instead means the paths exist once. */

	/** The square frame both derived icons are drawn in. */
	const FRAME = 800
	/**
	 * The logo's own intrinsic box — read from the file, not remembered.
	 *
	 * These were constants, 486 by 450, which are avenCEO's numbers. A brand
	 * whose mark is a different shape got it centred against someone else's
	 * dimensions and hanging off the frame. The SVG already states its size;
	 * a second copy of that fact could only ever be wrong.
	 */
	function logoBox(logoSvg: string): { width: number; height: number } {
		const viewBox = logoSvg.match(/viewBox="([\d.\s-]+)"/)
		if (viewBox) {
			const [, , width, height] = viewBox[1].trim().split(/\s+/).map(Number)
			if (width > 0 && height > 0) return { width, height }
		}
		const width = Number(logoSvg.match(/\bwidth="(\d+(?:\.\d+)?)"/)?.[1])
		const height = Number(logoSvg.match(/\bheight="(\d+(?:\.\d+)?)"/)?.[1])
		if (!(width > 0 && height > 0)) throw new Error('logo.svg states no viewBox or size')
		return { width, height }
	}

	/** Strip the outer `<svg …>` wrapper, keeping just the drawable children. */
	function logoBody(logoSvg: string): string {
		const opened = logoSvg.indexOf('>', logoSvg.indexOf('<svg'))
		const closed = logoSvg.lastIndexOf('</svg>')
		if (opened === -1 || closed === -1) throw new Error('logo.svg is not a well-formed <svg>')
		return logoSvg.slice(opened + 1, closed).trim()
	}

	/**
	 * Fit the logo to the square frame and centre it.
	 *
	 * Scaled as well as centred, because a mark twice the frame's width cannot be
	 * translated into view. `PADDING` keeps it off the edges at small sizes,
	 * where a favicon that touches its own border reads as a smudge.
	 */
	/** Drop trailing zeros, so an untouched icon stays byte-identical. */
	function trim(value: number, places = 2): string {
		return Number(value.toFixed(places)).toString()
	}

	const PADDING = 0.82
	function centred(logoSvg: string): string {
		const { width, height } = logoBox(logoSvg)
		/*
		 * Never ENLARGES. Fitting is about a mark that would overflow the frame,
		 * and scaling a smaller one up to fill it is a different decision — one
		 * that silently redrew avenCEO's favicon 35% bigger the first time this
		 * ran. A brand that wants its mark to fill the plate says so by drawing
		 * it that way.
		 */
		const scale = Math.min(1, (FRAME / Math.max(width, height)) * PADDING)
		const dx = (FRAME - width * scale) / 2
		const dy = (FRAME - height * scale) / 2
		const move = `translate(${trim(dx)}, ${trim(dy)})`
		const transform = scale === 1 ? move : `${move} scale(${trim(scale, 4)})`
		return `\t<g transform="${transform}">\n\t\t${logoBody(logoSvg)}\n\t</g>`
	}

	/**
	 * The app icon: the mark on a rounded plate, filled from a real brand cream.
	 * The plate colour used to be `#F8F1E8` — a fifth cream that belonged to no
	 * palette; it is the brand's own page ground now, like every other surface.
	 */
	function appIconSvg(logoSvg: string): string {
		return [
			`<svg width="${FRAME}" height="${FRAME}" viewBox="0 0 ${FRAME} ${FRAME}" fill="none" xmlns="http://www.w3.org/2000/svg">`,
			`\t<!-- GENERATED from assets/logo.svg by ${brand.name} — do not edit. -->`,
			`\t<rect width="${FRAME}" height="${FRAME}" rx="160" fill="${APP_ICON_PLATE}" />`,
			centred(logoSvg),
			'</svg>',
			''
		].join('\n')
	}

	/**
	 * The favicon: the clean mark, squared, on nothing. Every surface's `favicon.svg`
	 * is this file — replacing three different icons, two of which were SvelteKit's
	 * default template logo (`#ff3e00`) and one a hand-drawn monogram in colours
	 * (`#17251d` on `#f4f1e8`) that appeared in no palette.
	 */
	function faviconSvg(logoSvg: string): string {
		return [
			`<svg width="${FRAME}" height="${FRAME}" viewBox="0 0 ${FRAME} ${FRAME}" fill="none" xmlns="http://www.w3.org/2000/svg">`,
			`\t<!-- GENERATED from assets/logo.svg by ${brand.name} — do not edit. -->`,
			`\t<title>${brand.name}</title>`,
			centred(logoSvg),
			'</svg>',
			''
		].join('\n')
	}

	/* The palette comes back out with the generators, so a script can assert on
	   a value it is about to write without importing the brand a second time. */
	return { themeCss, componentCss, elementCss, appIconSvg, faviconSvg, CREAMS, TONES }
}

/** What `createGenerator` hands back. */
export type Generator = ReturnType<typeof createGenerator>
